<?php
/**
* copyright            : (C) 2001-2004 Advanced Internet Designs Inc.
* email                : forum@prohost.org
* $Id: errmsg.inc.t,v 1.8 2004/11/24 19:53:34 hackie Exp $
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
**/

define('__fud_ecore_adm_login_msg', '<br>Administrators can login <a href="'.$GLOBALS['WWW_ROOT'].'adm/admloginuser.php">here</a>');
define('__fud_e_install_script_present_error', 'For security reasons, you must remove the installation script at <b>'.$GLOBALS['WWW_ROOT_DISK'].'install.php</b> before you can use the forum.');
define('__fud_banned__', 'Your prior actions have resulted in you being permanently banned from this forum. Goodbye.');
?>